name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          pip install -q pipenv codecov
          pipenv sync --dev

      - name: Test with pytest and coverage
        run: pipenv run pytest --cov=curso-django

      - name: Rodar Flake8
        run: pipenv run flake8

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ CODECOV_TOKEN='d3bcb8c4-6f8f-4e06-8f25-d58b7c7fb334' }} # not required for public repos
