name: Python application

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          pip install -q pipenv codecov
          pipenv sync --dev


      - name: Test with pytest and coverage
        run: pipenv run pytest --cov=libpythonpro

      - name: Rodar Flake8
        run: pipenv run flake8

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

      version: 2
      updates:
      - package-ecosystem: pip
        directory: "/"
        schedule:
          interval: daily
        open-pull-requests-limit: 10